vms: []
vm_data: {}
vm_data_path: "{{ data0_path }}"
vm_volume_group: "{{ data_vg }}"
vm_images_path: "{{ data0_path }}/Linux-images"
vmfs_shares: {}
vm_network_bridge_name: host-bridge
vm_admin_network_device: virbr0
vm_admin_network_name: default
